### ISSUE TITLE
Use Properties

### ISSUE THREAD

**Issue by mayisa87** [milemihailov/MachineControlHub#1]
https://github.com/milemihailov/ControllingAndManagingApp/blob/c933b6fe464816cf96d9f2f2a52906af65a801c3/Bed/PrinterBed.cs#L5-L8

Please rewatch the video about properties and use them: https://course.raketementoring.com/courses/rakete-mentoring/lectures/45651742

There are some other videos about too, you can find them all in Module 7

**Comment by milemihailov** [comment]
this has been handled
